language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.3

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - wget https://phar.phpunit.de/phpunit-6.5.6.phar -O phpunit.phar

script: php phpunit.phar --configuration phpunit.travis.xml --coverage-text
